server:
  port: 8080
  servlet:
    context-path: /api


spring:
  transaction:
    default-timeout: 30
  profiles:
    active: local

  datasource:
    url: jdbc:h2:file:build/h2db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2


  jpa:
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true
    hibernate:
      ddl-auto: none
    database: h2

  jackson:
    serialization:
      write_dates_as_timestamps: false

logging:
  file: tw-nho29-service.log
  level:
    org.springframework.orm.jpa: info
    org.springframework.security.web.access.ExceptionTranslationFilter: debug
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql: info

